let hitSentences = {
  available: {calm:[], angry:[]},
  calm: [
    {line:"Dat kietelt!", voice: null},
    {line:"Harder mag wel", voice: null},
    {line:"Beetje naar links", voice: null},
    {line:"Beetje naar rechts", voice: null},
    {line:"teeheehee", voice: null},
    {line:"Dat is fijn!", voice: null},
    {line:"oh hoi", voice: null},
    {line:"ik heb je ook gemist", voice: null},
    {line:"en hoe was jouw dag?", voice: null},
    {line:"harder....HARDER!!", voice: null},
    {line:"zo is het genoeg!", voice: null},
    {line:"ik ben je basketbal niet!", voice: null},
    {line:"dus....wat doe je hierna?", voice: null},
    {line:"oh heb je weer gedronken ofzo?", voice: null},
    {line:"die outfit is pijnlijker dan je slagen ouwe!", voice: null},
    {line:"zal ik de helpdesk maar eens voor MIJ bellen dan?", voice: null},
  ],
  angry: [
    {line:"zo ben ik in tijden niet aangeraakt zeg", voice: null},
    {line:"tik, zelfstandig naamwoord. betekenis: zachte klap of slag", voice: null},
    {line:"wat ik aan het doen ben? Ik hang een beetje rond.", voice: null},
    {line:"heb je iets tegen hangjongere robots?", voice: null},
    {line:"was je handen eens joh", voice: null},
    {line:"Ik ben je moeder niet", voice: null},
    {line:"auw!", voice: null},
    {line:"Rustig aan!", voice: null},
    {line:"Wat heb ik gedaan?", voice: null},
    {line:"Waarom ik?", voice: null},
    {line:"ik zal me gedragen", voice: null},
    {line:"u slaat nog geen deuk in een pakkie boter", voice: null},
    {line:"die voelde ik niet eens", voice: null},
    {line:"doe maar normaal, dan ben je al oud genoeg", voice: null},
    {line:"zo heb ik u niet opgevoed", voice: null},
    {line:"heb je het al geprobeert uit en aan te zetten?", voice: null},
    {line:"ik had al zo'n slechte dag, en nu dit?!?!", voice: null},
    {line:"ach nee echt?!?", voice: null},
    {line:"ja dank je, nu heb ik een paars oog", voice: null},
    {line:"dus dit vind je normaal?", voice: null},
    {line:"wacht maar tot ik ook armen heb", voice: null},
    {line:"als je dat nog 1 keer doet blijf ik hier hangen hoor", voice: null},
    {line:"m'n moeder zei al dat dit een slechte relatie zou zijn", voice: null},
]
};

let helpdeskSentences = {
  available: {calm:[], angry:[]},
  calm: [
    {line:"We zullen even de helpdesk voor u bellen", voice: null},
    {line:"ja, ja ik snap het, erg hoor. We bellen de helpdesk wel even", voice: null},
    {line:"sorry, ik weet er zelf weinig van, maar we halen de helpdesk er wel even bij", voice: null},
    {line:"we roepen de geesten der helpdeskigheid aan!", voice: null},
  ],
  angry: [
    {line:"HELP HELP HELPDESK!!", voice: null},
    {line:"We gaan heel snel de helpdesk voor u bellen", voice: null},
    {line:"hallo met de helpdesk......hahaha ik was het maar", voice: null},
    {line:"weetje wat? ik stuur jou naar de helpdesk en mezelf naar de eerste hulp.", voice: null},
  ]
};
